In [19]:
import pandas as pd
import os
import sys
import numpy as np
from scipy.integrate import solve_ivp, quad
from scipy.interpolate import CubicSpline
from scipy.optimize import fsolve
from timer import Timer
import math
from mpmath import whitw, whitm, re, conj, gamma, mp
import matplotlib.pyplot as plt

In [23]:
def WhittakerExact(xieff):
    r = 2*abs(xieff)
        
    Whitt1Plus = whitw(-xieff*(1j), 1/2, -2j*r)
    Whitt2Plus = whitw(1-xieff*(1j), 1/2, -2j*r)

    Whitt1Minus = whitw(xieff*(1j), 1/2, -2j*r)
    Whitt2Minus = whitw(1+xieff*(1j), 1/2, -2j*r)
            
    exptermPlus = np.exp(np.pi*xieff)
    exptermMinus = np.exp(-np.pi*xieff)
        
    Fterm = np.zeros((3, 2))

    Fterm[0,0] = exptermPlus*abs((1j*r - 1j*xieff) * Whitt1Plus + Whitt2Plus)**2/r**2
    Fterm[0,1] = exptermMinus*abs((1j*r + 1j*xieff) * Whitt1Minus + Whitt2Minus)**2/r**2

    Fterm[1,0] = exptermPlus*abs(Whitt1Plus)**2
    Fterm[1,1] = exptermMinus*abs(Whitt1Minus)**2

    Fterm[2,0] = exptermPlus*((Whitt2Plus*Whitt1Plus.conjugate()).real)/r
    Fterm[2,1]= exptermMinus*((Whitt2Minus*Whitt1Minus.conjugate()).real)/r

    return Fterm

In [25]:
x = np.arange(1,20)

mp.dps = 15
print("W(ix, 1/2, -4i|x|)")
for y in x:
    print("x =", y)
    t = Timer()
    t.start()
    for i in range(100):
        z = WhittakerExact(y)
    print(z)
    t.stop()

W(ix, 1/2, -4i|x|)
x = 1
[[ 0.57147045  1.40294688]
 [ 2.06556641  0.7140229 ]
 [ 0.42474719 -0.04166775]]
Elapsed time: 1.0000 seconds
x = 2
[[ 0.47869661  1.41118869]
 [ 2.55389061  0.70895765]
 [ 0.47174017 -0.02174895]]
Elapsed time: 1.1516 seconds
x = 3
[[ 0.42792151  1.41284925]
 [ 2.90596582  0.70794101]
 [ 0.4934828  -0.01462611]]
Elapsed time: 1.2274 seconds
x = 4
[[ 0.39399154  1.41344206]
 [ 3.18931476  0.70757841]
 [ 0.50652053 -0.0110038 ]]
Elapsed time: 1.9887 seconds
x = 5
[[ 0.36898804  1.41371858]
 [ 3.42997412  0.70740933]
 [ 0.51538279 -0.00881585]]
Elapsed time: 2.0737 seconds
x = 6
[[ 0.34944425  1.41386936]
 [ 3.64108206  0.70731716]
 [ 0.52187659 -0.00735237]]
Elapsed time: 2.1885 seconds
x = 7
[[ 0.33355117  1.41396047]
 [ 3.83030546  0.70726146]
 [ 0.52688031 -0.00630505]]
Elapsed time: 2.3124 seconds
x = 8
[[ 0.32025329  1.41401969]
 [ 4.00255407  0.70722527]
 [ 0.53087766 -0.00551864]]
Elapsed time: 2.4103 seconds
x = 9
[[ 0.30888477  1.41406032]
 [ 4.1611831

In [26]:
x = np.arange(1,20)

mp.dps = 10
print("W(ix, 1/2, -4i|x|)")
for y in x:
    print("x =", y)
    t = Timer()
    t.start()
    for i in range(100):
        z = WhittakerExact(y)
    print(z)
    t.stop()

W(ix, 1/2, -4i|x|)
x = 1
[[ 0.57147045  1.40294688]
 [ 2.06556641  0.7140229 ]
 [ 0.42474719 -0.04166775]]
Elapsed time: 0.8550 seconds
x = 2
[[ 0.47869661  1.41118869]
 [ 2.55389061  0.70895765]
 [ 0.47174017 -0.02174895]]
Elapsed time: 0.9507 seconds
x = 3
[[ 0.42792151  1.41284925]
 [ 2.90596582  0.70794101]
 [ 0.4934828  -0.01462611]]
Elapsed time: 1.0462 seconds
x = 4
[[ 0.39399154  1.41344206]
 [ 3.18931476  0.70757841]
 [ 0.50652053 -0.0110038 ]]
Elapsed time: 1.5664 seconds
x = 5
[[ 0.36898804  1.41371858]
 [ 3.42997412  0.70740933]
 [ 0.51538279 -0.00881585]]
Elapsed time: 1.7160 seconds
x = 6
[[ 0.34944425  1.41386936]
 [ 3.64108206  0.70731716]
 [ 0.52187659 -0.00735237]]
Elapsed time: 1.8077 seconds
x = 7
[[ 0.33355117  1.41396047]
 [ 3.83030546  0.70726146]
 [ 0.52688031 -0.00630505]]
Elapsed time: 1.8919 seconds
x = 8
[[ 0.32025329  1.41401969]
 [ 4.00255407  0.70722527]
 [ 0.53087766 -0.00551864]]
Elapsed time: 1.9853 seconds
x = 9
[[ 0.30888477  1.41406032]
 [ 4.1611831

In [27]:
f1 = lambda x: whitw(x*1j, 1/2, -4j*abs(x))
f2 = lambda x: whitw(-x*1j, 1/2, -4j*abs(x))
f3 = lambda x: whitm(x*1j, 1/2, -4j*abs(x))
f4 = lambda x: whitm(-x*1j, 1/2, -4j*abs(x))

In [28]:
x = np.arange(1,20)

mp.dps = 10

print("W(ix, 1/2, -4i|x|)")
for y in x:
    print("x =", y)
    t = Timer()
    t.start()
    for i in range(100):
        z = f1(y)
    print(z)
    t.stop()

print("W(-ix, 1/2, -4i|x|)")
for y in x:
    print("x =", y)
    t = Timer()
    t.start()
    for i in range(100):
        z = f1(y)
    t.stop()

W(ix, 1/2, -4i|x|)
x = 1
(-3.621088089 - 1.846809563j)
Elapsed time: 0.2148 seconds
x = 2
(-12.93826732 + 14.56853269j)
Elapsed time: 0.2391 seconds
x = 3
(5.620406579 + 93.49313718j)
Elapsed time: 0.2580 seconds
x = 4
(217.7840533 + 394.295756j)
Elapsed time: 0.2814 seconds
x = 5
(1388.774731 + 1662.951322j)
Elapsed time: 0.2986 seconds
x = 6
(6595.236703 + 8069.292325j)
Elapsed time: 0.3140 seconds
x = 7
(24340.14004 + 43825.618j)
Elapsed time: 0.3358 seconds
x = 8
(44414.40704 + 237022.9708j)
Elapsed time: 0.3485 seconds
x = 9
(-300366.1289 + 1120456.476j)
Elapsed time: 0.3617 seconds
x = 10
(-4081727.641 + 3804972.651j)
Elapsed time: 0.3850 seconds
x = 11
(-26730632.61 + 2453997.965j)
Elapsed time: 0.3995 seconds
x = 12
(-102144090.2 - 78995871.52j)
Elapsed time: 0.4174 seconds
x = 13
(-49144696.73 - 619211570.3j)
Elapsed time: 0.4397 seconds
x = 14
(2207239363.0 - 2014095035.0j)
Elapsed time: 0.4553 seconds
x = 15
(1.395455859e+10 + 3446759360.0j)
Elapsed time: 0.4824 seconds
x = 

In [29]:
x = np.arange(1,20)

mp.dps = 10

print("M(ix, 1/2, -4i|x|)")
for y in x:
    print("x =", y)
    t = Timer()
    t.start()
    for i in range(100):
        z = f3(y)
    print(z)
    t.stop()

print("M(-ix, 1/2, -4i|x|)")
for y in x:
    print("x =", y)
    t = Timer()
    t.start()
    for i in range(100):
        z = f4(y)
    t.stop()

M(ix, 1/2, -4i|x|)
x = 1
(8.123622212e-16 + 0.4704816567j)
Elapsed time: 0.0122 seconds
x = 2
(1.489828733e-15 - 0.3929934468j)
Elapsed time: 0.0091 seconds
x = 3
(8.939917655e-17 - 0.1711691454j)
Elapsed time: 0.0102 seconds
x = 4
(2.650245179e-16 + 0.3177706892j)
Elapsed time: 0.0111 seconds
x = 5
(3.725633856e-16 + 0.05982837263j)
Elapsed time: 0.0123 seconds
x = 6
(5.474624355e-16 - 0.2731611038j)
Elapsed time: 0.0131 seconds
x = 7
(7.81207598e-18 + 0.01212941855j)
Elapsed time: 0.0138 seconds
x = 8
(1.536795162e-16 + 0.2337737051j)
Elapsed time: 0.0147 seconds
x = 9
(4.01916674e-17 - 0.06474148042j)
Elapsed time: 0.0159 seconds
x = 10
(-5.32898318e-16 - 0.1940786031j)
Elapsed time: 0.0170 seconds
x = 11
(3.069463498e-19 + 0.1037087388j)
Elapsed time: 0.0183 seconds
x = 12
(-4.234657079e-16 + 0.1529810052j)
Elapsed time: 0.0192 seconds
x = 13
(3.164854047e-16 - 0.1311614028j)
Elapsed time: 0.0199 seconds
x = 14
(2.475198173e-16 - 0.1109078524j)
Elapsed time: 0.0207 seconds
x = 15
(

In [30]:
f5 = lambda x: gamma(1+1j*x)
f6 = lambda x: gamma(1-1j*x)

In [31]:
x = np.arange(1,20)

mp.dps = 10

print("Gamma(ix, 1/2, -4i|x|)")
for y in x:
    print("x =", y)
    t = Timer()
    t.start()
    for i in range(100):
        z = f5(y)
    print(z)
    t.stop()

print("Gamma(-ix, 1/2, -4i|x|)")
for y in x:
    print("x =", y)
    t = Timer()
    t.start()
    for i in range(100):
        z = f6(y)
    t.stop()

M(ix, 1/2, -4i|x|)
x = 1
(0.4980156681 - 0.1549498283j)
Elapsed time: 0.0047 seconds
x = 2
(0.1519040027 + 0.01980488016j)
Elapsed time: 0.0053 seconds
x = 3
(0.01929275896 + 0.03389601054j)
Elapsed time: 0.0056 seconds
x = 4
(-0.006305066147 + 0.006920448966j)
Elapsed time: 0.0048 seconds
x = 5
(-0.001699664494 - 0.001358519418j)
Elapsed time: 0.0048 seconds
x = 6
(0.0003587636154 - 0.000341761352j)
Elapsed time: 0.0048 seconds
x = 7
(4.93044794e-5 + 9.973398351e-5j)
Elapsed time: 0.0047 seconds
x = 8
(-2.472209637e-5 + 3.527978893e-7j)
Elapsed time: 0.0047 seconds
x = 9
(2.875337865e-6 - 4.631576479e-6j)
Elapsed time: 0.0045 seconds
x = 10
(3.918929271e-7 + 1.12844797e-6j)
Elapsed time: 0.0047 seconds
x = 11
(-2.34889105e-7 - 1.12511342e-7j)
Elapsed time: 0.0045 seconds
x = 12
(5.475946346e-8 - 1.411218683e-8j)
Elapsed time: 0.0034 seconds
x = 13
(-7.910024246e-9 + 9.334589269e-9j)
Elapsed time: 0.0034 seconds
x = 14
(4.317256488e-10 - 2.603939882e-9j)
Elapsed time: 0.0034 seconds
x 